name: Jentacular
options:
  bundleIdPrefix: com.hitvpn
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    ONLY_ACTIVE_ARCH: YES
    MARKETING_VERSION: "1.1"
    CURRENT_PROJECT_VERSION: "124"
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: S47SL2JFSQ
    CODE_SIGN_IDENTITY: "Apple Distribution"
    PROVISIONING_PROFILE_SPECIFIER: "hitvpn2026_AppStore_NewCert0930"
targets:
  Jentacular:
    type: application
    platform: iOS
    sources:
      - path: Jentacular
    resources:
      - path: Jentacular/Resources/Assets.xcassets
      - path: Jentacular/Resources/PrivacyInfo.xcprivacy
      - path: Jentacular/Resources/en.lproj
      - path: Jentacular/Resources/ru.lproj
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hitvpn.hitvpn2026
        PRODUCT_NAME: Jentacular
        INFOPLIST_FILE: Jentacular/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Jentacular/Resources/Jentacular.entitlements
    info:
      path: Jentacular/Resources/Info.plist
      properties:
        CFBundleDisplayName: Jentacular vpn
        CFBundleShortVersionString: "1.1"
        CFBundleVersion: "124"
        ITSAppUsesNonExemptEncryption: false
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIRequiresFullScreen: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
